const STORE={LOGS:"qomplete_logs",PLAN:"q_plan",CHALLENGE:"q_challenge"};
const GOALS={steps:8000,water:3};
const DAYS=[["MO","Montag"],["TU","Dienstag"],["WE","Mittwoch"],["TH","Donnerstag"],["FR","Freitag"],["SA","Samstag"],["SU","Sonntag"]];
const dayIndex={MO:1,TU:2,WE:3,TH:4,FR:5,SA:6,SU:0};
const defaultPlan={timeMeal1:"09:00",timeFood1:"12:30",timeQore:"15:00",timeWalk:"17:00",timeFood2:"18:30",timeMeal2:"20:30",training:{MO:{on:false,time:"18:00"},TU:{on:false,time:"18:00"},WE:{on:false,time:"18:00"},TH:{on:false,time:"18:00"},FR:{on:false,time:"18:00"},SA:{on:false,time:"11:00"},SU:{on:false,time:"11:00"}},mounjaroDay:"SU",mounjaroTime:"10:00",reviewDay:"SU",reviewTime:"10:15"};
const defaultChallenge={started:false,startDate:null,startWeight:null,targetWeight:95};
const missionNormal=["Wiegen","Qomplete Meal #1","Mahlzeit 1","QORE","30 Min Spaziergang","Mahlzeit 2","Qomplete Meal #2","2-3 Liter Wasser","Training, falls geplant","7,5 Std. Bettzeit planen"];
const missionBad=["Wiegen","Qomplete Meal #1","QORE","Qomplete Meal #2","Wasser","10 Minuten Bewegung"];
let badDay=false;

function todayISO(){return new Date().toISOString().slice(0,10)}
function clone(x){return JSON.parse(JSON.stringify(x))}
function read(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):clone(fallback)}catch(e){return clone(fallback)}}
function write(key,val){localStorage.setItem(key,JSON.stringify(val))}
function loadLogs(){return read(STORE.LOGS,[]).sort((a,b)=>a.date.localeCompare(b.date))}
function saveLogs(logs){write(STORE.LOGS,logs.sort((a,b)=>a.date.localeCompare(b.date)))}
function getPlan(){return read(STORE.PLAN,defaultPlan)}
function savePlan(p){write(STORE.PLAN,p)}
function getChallenge(){return read(STORE.CHALLENGE,defaultChallenge)}
function saveChallenge(c){write(STORE.CHALLENGE,c)}
function avg(arr){const nums=arr.filter(x=>typeof x==="number"&&!isNaN(x));return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null}
function fmt(n,d=1){return n===null||n===undefined||isNaN(n)?"–":Number(n).toFixed(d)}
function pct(v,g){return(!v||!g)?0:Math.max(0,Math.min(100,v/g*100))}
function latest(logs){return logs.length?logs[logs.length-1]:null}
function rolling7(logs,idx){return avg(logs.slice(Math.max(0,idx-6),idx+1).map(x=>x.weight))}
function upsertLog(date,patch){const logs=loadLogs();const old=logs.find(x=>x.date===date)||{date};const next=logs.filter(x=>x.date!==date);next.push({...old,...patch,date});saveLogs(next)}
function checksKey(){return"q_checks_"+todayISO()}
function getChecks(){return read(checksKey(),{})}
function setChecks(c){write(checksKey(),c)}

function initPlanner(){const box=document.getElementById("trainingPlan");box.innerHTML="";DAYS.forEach(([k,n])=>{const d=document.createElement("div");d.className="day-card";d.innerHTML=`<label><input id="tr_${k}" type="checkbox"> ${n}</label><input id="trtime_${k}" type="time">`;box.appendChild(d)});["mounjaroDay","reviewDay"].forEach(id=>{const s=document.getElementById(id);s.innerHTML="";DAYS.forEach(([k,n])=>{const o=document.createElement("option");o.value=k;o.textContent=n;s.appendChild(o)})})}
function loadPlannerInputs(){const p=getPlan();["timeMeal1","timeFood1","timeQore","timeWalk","timeFood2","timeMeal2","mounjaroTime","reviewTime"].forEach(id=>document.getElementById(id).value=p[id]||"");document.getElementById("mounjaroDay").value=p.mounjaroDay||"SU";document.getElementById("reviewDay").value=p.reviewDay||"SU";DAYS.forEach(([k])=>{document.getElementById("tr_"+k).checked=!!p.training?.[k]?.on;document.getElementById("trtime_"+k).value=p.training?.[k]?.time||"18:00"})}
function readPlannerInputs(){const p=clone(defaultPlan);["timeMeal1","timeFood1","timeQore","timeWalk","timeFood2","timeMeal2","mounjaroTime","reviewTime"].forEach(id=>p[id]=document.getElementById(id).value);p.mounjaroDay=document.getElementById("mounjaroDay").value;p.reviewDay=document.getElementById("reviewDay").value;p.training={};DAYS.forEach(([k])=>p.training[k]={on:document.getElementById("tr_"+k).checked,time:document.getElementById("trtime_"+k).value||"18:00"});return p}
function loadChallengeInputs(){const c=getChallenge();document.getElementById("challengeStartDate").value=c.startDate||todayISO();document.getElementById("challengeStartWeight").value=c.startWeight||"";document.getElementById("challengeTargetWeight").value=c.targetWeight||95}

function renderTimeline(){const p=getPlan();const daily=[{time:p.timeMeal1,label:"Qomplete Meal #1 + Wasser + Wiegen"},{time:p.timeFood1,label:"Mahlzeit 1, proteinreich"},{time:p.timeQore,label:"QORE"},{time:p.timeWalk,label:"30 Min Spaziergang"},{time:p.timeFood2,label:"Mahlzeit 2, proteinreich"},{time:p.timeMeal2,label:"Qomplete Meal #2"}].filter(x=>x.time).sort((a,b)=>a.time.localeCompare(b.time));const train=Object.entries(p.training||{}).filter(([k,v])=>v.on).map(([k,v])=>`${DAYS.find(d=>d[0]===k)[1]} ${v.time}`).join(" · ")||"noch nicht geplant";const fixed=`${DAYS.find(d=>d[0]===p.mounjaroDay)[1]} ${p.mounjaroTime} Mounjaro · ${DAYS.find(d=>d[0]===p.reviewDay)[1]} ${p.reviewTime} Wochenreview`;const h=daily.map(x=>`<div><b>${x.time}</b><span>${x.label}</span></div>`).join("")+`<div><b>Training</b><span>${train}</span></div><div><b>Fixpunkte</b><span>${fixed}</span></div>`;document.getElementById("timeline").innerHTML=h;document.getElementById("calendarPreview").innerHTML=h}
function renderMission(){const list=badDay?missionBad:missionNormal;const c=getChecks();const box=document.getElementById("mission");box.innerHTML="";list.forEach(item=>{const row=document.createElement("label");row.className="check";row.innerHTML=`<input type="checkbox" ${c[item]?"checked":""}> <span>${item}</span>`;box.appendChild(row);row.querySelector("input").addEventListener("change",e=>{c[item]=e.target.checked;setChecks(c);renderScore()})})}
function renderScore(){const list=badDay?missionBad:missionNormal,c=getChecks(),done=list.filter(x=>c[x]).length,total=list.length,p=total?Math.round(done/total*100):0;document.getElementById("scoreText").textContent=`${done} / ${total}`;document.getElementById("routineBar").style.width=p+"%";document.getElementById("routineText").textContent=p+"%";document.getElementById("scoreStatus").textContent=p>=80?"Stark. Heute ist auf Kurs.":p>=50?"Solide. Weiter abhaken.":p>0?"Angefangen. Nächster Haken zählt.":"Noch nichts erledigt"}
function renderChallenge(logs){const c=getChallenge(),status=document.getElementById("challengeStatus"),text=document.getElementById("weightProgressText"),bar=document.getElementById("weightProgressBar");if(!c.started){status.textContent="Noch nicht gestartet";text.textContent="Startdatum festlegen und Challenge starten.";bar.style.width="0%";return{label:"Nicht gestartet",remaining:"Start festlegen"}}const day=Math.min(90,Math.max(1,Math.floor((new Date()-new Date(c.startDate))/(1000*60*60*24))+1)),rem=Math.max(0,90-day),cur=latest(logs)?.weight||c.startWeight,total=c.startWeight-c.targetWeight,lost=c.startWeight-cur,percent=total>0?Math.max(0,Math.min(100,lost/total*100)):0;status.textContent=`Läuft seit ${c.startDate} · Tag ${day} / 90`;text.textContent=`Start ${fmt(c.startWeight)} kg · aktuell ${fmt(cur)} kg · Ziel ${fmt(c.targetWeight)} kg · verloren ${fmt(lost)} kg`;bar.style.width=percent+"%";return{label:`Tag ${day} / 90`,remaining:`${rem} Tage übrig`}}
function renderTable(logs){const body=document.getElementById("logBody");body.innerHTML="";[...logs].reverse().slice(0,30).forEach(r=>{const idx=logs.findIndex(x=>x.date===r.date),m=r.moodEvening||r.moodMorning||"";const tr=document.createElement("tr");tr.innerHTML=`<td>${r.date}</td><td>${fmt(r.weight)} kg</td><td>${fmt(rolling7(logs,idx))} kg</td><td>${r.steps||""}</td><td>${r.water||""}</td><td>${m}</td><td><button onclick="deleteLog('${r.date}')">Löschen</button></td>`;body.appendChild(tr)})}
function deleteLog(date){saveLogs(loadLogs().filter(x=>x.date!==date));render()}
function drawChart(logs){const canvas=document.getElementById("chart"),ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);const data=logs.filter(x=>x.weight).slice(-60);if(data.length<2){ctx.fillStyle="#b7b0a1";ctx.font="18px Arial";ctx.fillText("Trage ein paar Tage Gewicht ein, dann erscheint hier der Verlauf.",28,130);return}const weights=data.map(x=>x.weight),min=Math.min(...weights)-1,max=Math.max(...weights)+1,pad=34,W=canvas.width-pad*2,H=canvas.height-pad*2;function x(i){return pad+i/(data.length-1)*W}function y(v){return pad+(max-v)/(max-min)*H}ctx.strokeStyle="#394236";ctx.lineWidth=1;for(let i=0;i<5;i++){let yy=pad+i*H/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(pad+W,yy);ctx.stroke()}ctx.strokeStyle="#d7b56d";ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{i?ctx.lineTo(x(i),y(d.weight)):ctx.moveTo(x(i),y(d.weight))});ctx.stroke();const avgs=data.map((_,i)=>avg(data.slice(Math.max(0,i-6),i+1).map(x=>x.weight)));ctx.strokeStyle="#7fc97f";ctx.lineWidth=3;ctx.beginPath();avgs.forEach((v,i)=>{i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v))});ctx.stroke();ctx.fillStyle="#b7b0a1";ctx.font="14px Arial";ctx.fillText("Gold = Tagesgewicht, Grün = 7-Tage-Schnitt",pad,22)}
function render(){const logs=loadLogs(),l=latest(logs);document.getElementById("latestWeight").textContent=l?.weight?fmt(l.weight)+" kg":"– kg";const avg7=logs.length?avg(logs.slice(-7).map(x=>x.weight)):null;document.getElementById("avg7").textContent=avg7?fmt(avg7)+" kg":"– kg";const c7=avg(logs.slice(-7).map(x=>x.weight)),p7=avg(logs.slice(-14,-7).map(x=>x.weight)),tr=c7&&p7?c7-p7:null;document.getElementById("trend").textContent=tr===null?"–":(tr<0?"↓ ":"↑ ")+fmt(Math.abs(tr))+" kg";const ch=renderChallenge(logs);document.getElementById("dayCount").textContent=ch.label;document.getElementById("remainingDays").textContent=ch.remaining;document.getElementById("date").value=todayISO();const today=logs.find(x=>x.date===todayISO())||{},w=today.water||0,s=today.steps||0;document.getElementById("waterBar").style.width=pct(w,GOALS.water)+"%";document.getElementById("stepsBar").style.width=pct(s,GOALS.steps)+"%";document.getElementById("waterText").textContent=w?`${w}/${GOALS.water}L`:"–";document.getElementById("stepsText").textContent=s?`${s}/${GOALS.steps}`:"–";renderTimeline();renderMission();renderScore();renderTable(logs);drawChart(logs)}
function startChallenge(){const date=document.getElementById("challengeStartDate").value||todayISO();let sw=parseFloat(document.getElementById("challengeStartWeight").value);const tw=parseFloat(document.getElementById("challengeTargetWeight").value)||95;if(!sw)sw=latest(loadLogs())?.weight;if(!sw){alert("Startgewicht fehlt.");return}saveChallenge({started:true,startDate:date,startWeight:sw,targetWeight:tw});render()}
function resetChallenge(){if(!confirm("Challenge zurücksetzen? Gewichtseinträge bleiben erhalten."))return;saveChallenge(clone(defaultChallenge));loadChallengeInputs();render()}
function deleteAllData(){if(!confirm("Wirklich ALLE App-Daten löschen?"))return;if(!confirm("Letzte Sicherheitsfrage: Das kann nicht rückgängig gemacht werden."))return;Object.keys(localStorage).forEach(k=>{if(k.startsWith("q_")||k===STORE.LOGS)localStorage.removeItem(k)});loadPlannerInputs();loadChallengeInputs();render()}
function nextDateFor(key){const now=new Date(),d=new Date(now),diff=(dayIndex[key]+7-now.getDay())%7;d.setDate(now.getDate()+(diff||7));return d}
function dateWithTime(base,time){const [h,m]=time.split(":").map(Number),d=new Date(base);d.setHours(h||0,m||0,0,0);return d}
function icsDate(d){const p=n=>String(n).padStart(2,"0");return d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+"T"+p(d.getHours())+p(d.getMinutes())+"00"}
function uid(){return Date.now()+"-"+Math.random().toString(16).slice(2)+"@max-qomplete"}
function alarm(m){return["BEGIN:VALARM","ACTION:DISPLAY","DESCRIPTION:Erinnerung","TRIGGER:-PT"+m+"M","END:VALARM"].join("\\r\\n")}
function event(title,start,minutes,rrule,rem){const lines=["BEGIN:VEVENT","UID:"+uid(),"SUMMARY:"+title,"DTSTART;TZID=Europe/Berlin:"+icsDate(start)];if(minutes){const end=new Date(start.getTime()+minutes*60000);lines.push("DTEND;TZID=Europe/Berlin:"+icsDate(end))}if(rrule)lines.push("RRULE:"+rrule);lines.push(alarm(rem));lines.push("END:VEVENT");return lines.join("\\r\\n")}
function downloadICS(){const p=getPlan(),base=new Date();base.setDate(base.getDate()+1);const events=[];[["Qomplete Meal #1",p.timeMeal1],["Mahlzeit 1",p.timeFood1],["QORE trinken",p.timeQore],["Spaziergang starten",p.timeWalk],["Mahlzeit 2",p.timeFood2],["Qomplete Meal #2",p.timeMeal2]].forEach(([t,time])=>{if(time)events.push(event(t,dateWithTime(base,time),1,"FREQ=DAILY;COUNT=90",10))});Object.entries(p.training||{}).forEach(([k,v])=>{if(v.on&&v.time)events.push(event("Krafttraining",dateWithTime(nextDateFor(k),v.time),75,"FREQ=WEEKLY;COUNT=13",30))});if(p.mounjaroTime)events.push(event("Mounjaro",dateWithTime(nextDateFor(p.mounjaroDay),p.mounjaroTime),1,"FREQ=WEEKLY;COUNT=13",60));if(p.reviewTime)events.push(event("Wochenreview",dateWithTime(nextDateFor(p.reviewDay),p.reviewTime),20,"FREQ=WEEKLY;COUNT=13",15));const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Max Qomplete Dashboard//DE","CALSCALE:GREGORIAN","METHOD:PUBLISH",...events,"END:VCALENDAR"].join("\\r\\n");const blob=new Blob([ics],{type:"text/calendar;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="max_qomplete_routinen_mit_erinnerungen.ics";a.click();URL.revokeObjectURL(url)}
function exportBackup(){const data={version:"7.1",exportedAt:new Date().toISOString(),logs:loadLogs(),plan:getPlan(),challenge:getChallenge(),checks:Object.keys(localStorage).filter(k=>k.startsWith("q_checks_")).reduce((a,k)=>{a[k]=read(k,{});return a},{})};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="max_qomplete_backup.json";a.click();URL.revokeObjectURL(url)}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.logs)saveLogs(d.logs);if(d.plan)savePlan(d.plan);if(d.challenge)saveChallenge(d.challenge);if(d.checks)Object.entries(d.checks).forEach(([k,v])=>write(k,v));loadPlannerInputs();loadChallengeInputs();render();alert("Backup importiert.")}catch(e){alert("Import fehlgeschlagen.")}};r.readAsText(file)}

document.addEventListener("DOMContentLoaded",()=>{initPlanner();loadPlannerInputs();loadChallengeInputs();document.getElementById("savePlanBtn").onclick=()=>{savePlan(readPlannerInputs());render();alert("Plan gespeichert.")};document.getElementById("saveMorningBtn").onclick=()=>{const date=document.getElementById("date").value||todayISO(),weight=parseFloat(document.getElementById("weight").value),moodMorning=parseInt(document.getElementById("moodMorning").value)||null;if(!date||!weight){alert("Datum und Gewicht müssen rein.");return}upsertLog(date,{weight,moodMorning});const c=getChecks();c["Wiegen"]=true;setChecks(c);document.getElementById("weight").value="";document.getElementById("moodMorning").value="";render()};document.getElementById("saveEveningBtn").onclick=()=>{const date=document.getElementById("date").value||todayISO(),steps=parseInt(document.getElementById("steps").value)||null,water=parseFloat(document.getElementById("water").value)||null,moodEvening=parseInt(document.getElementById("moodEvening").value)||null;upsertLog(date,{steps,water,moodEvening});document.getElementById("steps").value="";document.getElementById("water").value="";document.getElementById("moodEvening").value="";render()};document.getElementById("startChallengeBtn").onclick=startChallenge;document.getElementById("resetChallengeBtn").onclick=resetChallenge;document.getElementById("deleteAllBtn").onclick=deleteAllData;document.getElementById("calendarBtn").onclick=()=>window.open("https://calendar.google.com/calendar/u/0/r","_blank");document.getElementById("icsBtn").onclick=downloadICS;document.getElementById("exportBtn").onclick=exportBackup;document.getElementById("importBtn").onclick=()=>document.getElementById("importFile").click();document.getElementById("importFile").onchange=e=>{if(e.target.files&&e.target.files[0])importBackup(e.target.files[0])};document.getElementById("badDayBtn").onclick=()=>{badDay=!badDay;document.getElementById("badDayBtn").textContent=badDay?"Normaler Tag":"Schlechter Tag";renderMission();renderScore()};render()});
